-- 1. 기존 컬럼 타입 변경 (INT -> BIGINT)
ALTER TABLE TB_CORP_FINANCE MODIFY op_income BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY investment BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY net_income BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY revenue BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY total_asset BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY total_debt BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY total_capital BIGINT;
ALTER TABLE TB_CORP_FINANCE MODIFY income_before_tax BIGINT;

-- 2. 새로운 성장성 지표 비교용 컬럼 추가
ALTER TABLE TB_CORP_FINANCE ADD COLUMN prev_op_income BIGINT;
ALTER TABLE TB_CORP_FINANCE ADD COLUMN prev_net_income BIGINT;
ALTER TABLE TB_CORP_FINANCE ADD COLUMN prev_revenue BIGINT;

-- 3. PK 변경 (corp_code -> corp_code + bas_dt)
-- 기존 PK 제약조건 삭제 (MySQL/H2 호환)
ALTER TABLE TB_CORP_FINANCE DROP PRIMARY KEY;

-- 복합키 설정
ALTER TABLE TB_CORP_FINANCE ADD PRIMARY KEY (corp_code, bas_dt);
